name: feed_app_riverpod
description: Demo feed app with Riverpod
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  feed_lib:
    path: ../feed_lib

  flutter_riverpod: ^2.0.0-dev.5
  go_router: ^3.0.5
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  feed_test_lib:
    path: ../feed_test_lib

  flutter_lints: ^1.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true