// Helper file to make coverage work for all dart files
// **************************************************************************
// Because of this: https://github.com/flutter/flutter/issues/27997#issue-410722816
// DO NOT EDIT THIS FILE USE: sh scripts/import_files_coverage.sh feed_app
// **************************************************************************

// ignore_for_file: unused_import
import 'package:feed_app/router.dart';
import 'package:feed_app/screens/error_screen.dart';
import 'package:feed_app/screens/feedlist_controller.dart';
import 'package:feed_app/screens/login_screen.dart';
import 'package:feed_app/screens/home_screen.dart';
import 'package:feed_app/screens/detail_screen.dart';
import 'package:feed_app/main.dart';

void main(){}