// Helper file to make coverage work for all dart files
// **************************************************************************
// Because of this: https://github.com/flutter/flutter/issues/27997#issue-410722816
// DO NOT EDIT THIS FILE USE: sh scripts/import_files_coverage.sh feed_app
// **************************************************************************

// ignore_for_file: unused_import
import 'package:feed_app_cubit/router.dart';
import 'package:feed_app_cubit/screens/auth_cubit.dart';
import 'package:feed_app_cubit/screens/error_screen.dart';
import 'package:feed_app_cubit/screens/message_cubits.dart';
import 'package:feed_app_cubit/screens/login_screen.dart';
import 'package:feed_app_cubit/screens/home_screen.dart';
import 'package:feed_app_cubit/screens/detail_screen.dart';
import 'package:feed_app_cubit/main.dart';

void main(){}