// Helper file to make coverage work for all dart files
// **************************************************************************
// Because of this: https://github.com/flutter/flutter/issues/27997#issue-410722816
// DO NOT EDIT THIS FILE USE: sh scripts/import_files_coverage.sh feed_app
// **************************************************************************

// ignore_for_file: unused_import
import 'package:feed_lib/feed_lib.dart';
import 'package:feed_lib/src/model/message.dart';
import 'package:feed_lib/src/model/user.dart';
import 'package:feed_lib/src/controllers/auth_controller.dart';
import 'package:feed_lib/src/services/client.dart';
import 'package:feed_lib/src/services/async_task.dart';
import 'package:feed_lib/src/services/auth_service.dart';
import 'package:feed_lib/src/services/feed_service.dart';
import 'package:feed_lib/src/widgets/message_tile.dart';
import 'package:feed_lib/src/widgets/buttons.dart';
import 'package:feed_lib/src/widgets/new_messages.dart';
import 'package:feed_lib/src/widgets/appbar.dart';

void main(){}