// Helper file to make coverage work for all dart files
// **************************************************************************
// Because of this: https://github.com/flutter/flutter/issues/27997#issue-410722816
// DO NOT EDIT THIS FILE USE: sh scripts/import_files_coverage.sh feed_app
// **************************************************************************

// ignore_for_file: unused_import
import 'package:feed_app_riverpod/screens/error_screen.dart';
import 'package:feed_app_riverpod/screens/feedlist_controller.dart';
import 'package:feed_app_riverpod/screens/login_screen.dart';
import 'package:feed_app_riverpod/screens/home_screen.dart';
import 'package:feed_app_riverpod/screens/detail_screen.dart';
import 'package:feed_app_riverpod/main.dart';
import 'package:feed_app_riverpod/providers.dart';

void main(){}